version: '3'
services:

    php:
        image: atillay/lemp-php
        env_file:
            - .env
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var
    composer:
        image: "composer"
        volumes:
            - ./www:/app
        command: install

    nginx:
        image: atillay/lemp-nginx
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./www:/var/www

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - persistent:/var/lib/mysql
volumes:
    persistent:
